

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def gen_fib(thresh):

	fib_list = [1,2]
	i = 2
	while fib_list[i-1] < thresh:
	 	fib_list.append(fib_list[i-1]+fib_list[i-2])
	 	i += 1
	fib_list.pop()
	return fib_list

#filter function
def f(x): return x % 2 == 0

thresh = 4000000
fib_list = gen_fib(thresh)
print "Even Fibonacci numbers to:", thresh
print filter(f, fib_list)
print "Sum:", sum(filter(f, fib_list))
